// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnoAcademyApi.Data;

#nullable disable

namespace TechnoAcademyApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230823054125_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TechnoAcademyApi.Models.FormRegister", b =>
                {
                    b.Property<string>("UUID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Cv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Ipk")
                        .HasColumnType("float");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prodi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<bool>("StatusMahasiswa")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Universitas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UUID");

                    b.ToTable("FormRegisters");
                });
#pragma warning restore 612, 618
        }
    }
}
